modLoader = "javafml"
loaderVersion = "[49,)"
issueTrackerURL = "https://github.com/someElseIsHere/yeat-the-sheep/issues"
license = "GPL-3.0"

[[mods]]
modId = "yeatthesheep"
version = "${version}"
displayName = "Yeat the Sheep !"
authors = "thePlaceholder"
description = '''
Get wool by yeating sheeps!
'''
logoFile = "logo.png"

[[dependencies.yeatthesheep]]
modId = "forge"
mandatory = true
versionRange = "[49,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yeatthesheep]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"