modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/someElseIsHere/yeat-the-sheep/issues"
license = "GPL-3.0"

[[mods]]
modId = "yeatthesheep"
version = "${version}"
displayName = "Yeat the Sheep !"
authors = "thePlaceholder"
description = '''
Get wool by yeating sheeps!
'''
logoFile = "logo.png"

[[dependencies.yeatthesheep]]
modId = "neoforge"
type="required"
versionRange = "[21.0.0-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.yeatthesheep]]
modId = "minecraft"
type="required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "yeatthesheep.mixins.json"